name: Build and Push Windows Docker Image to ECR

on:
  push:

jobs:
  buildx:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: StefanScherer/dockerfiles-windows
          path: webserver

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Change to your region

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: webserver
          push: true
          tags: ${{ steps.ecr-login.outputs.registry }}/github-build:latest
          file: webserver/Dockerfile
