name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Trigger the workflow when there's a push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    #runs-on: windows-latest  # This workflow will run on a Windows runner
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
    # - name: Check out the repository
    #   uses: actions/checkout@v3

    - name: Super-linter
      uses: super-linter/super-linter@v6.5.0  # x-release-please-version
      env:
        # To report GitHub Actions status checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 973905176396.dkr.ecr.us-west-2.amazonaws.com

    # - name: Build Docker image
    #   run: |
    #     docker build . -t 973905176396.dkr.ecr.us-west-2.amazonaws.com/github-build:latest

    # - name: Push Docker image to Amazon ECR
    #   run: |
    #     docker push 973905176396.dkr.ecr.us-west-2.amazonaws.com/github-build:latest

    # - name: Deploy to Amazon ECS
    #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
    #   with:
    #     task-definition: windows1-revision1.json
    #     service: window1
    #     cluster: fargate
    #     wait-for-service-stability: true


  