name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Trigger the workflow when there's a push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: windows-latest  # This workflow will run on a Windows runner

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to Amazon ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 973905176396.dkr.ecr.us-west-2.amazonaws.com

    - name: Build Docker image
      run: |
        docker build . -t 973905176396.dkr.ecr.us-west-2.amazonaws.com/github-build:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push 973905176396.dkr.ecr.us-west-2.amazonaws.com/github-build:latest
